### PR TITLE
Student scheduling

### PR DESCRIPTION
**Pull request by CameronBourque**
Student scheduler now works in users controller. Tests are made for it as well as unit tests for the user model. Updated some validations for the user model as well.

### CODE REVIEW

**Comment by CameronBourque** [comment]
We should do a rubocop -A in dev. There's a lot of issues to resolve that aren't marked here. It will also be easier to manage the merge conflicts as well.

**Comment by CameronBourque** [comment]
Doing the merge made rubocop easier for me. So wait on the push with rubocop -a for the fix before merging.

**Comment by CameronBourque** [comment]
The rubocop failures here are not from the pushed code.

**Comment by CameronBourque** [comment]
Removed the student controller and associated files. Made a new index page attached to the users controller.

**Comment by CameronBourque** [comment]
most recent commit breaks some tests so hold on

**Comment by CameronBourque** [comment]
I'm just keeping this updated with dev merges to make sure integration stays smooth

**Review by baileyjrob — APPROVED** [review]

**Pull request merged**
